### ISSUE TITLE
Base

### ISSUE THREAD

**Issue by prekucki** [golemfactory/gprocess-man#1]
- [x] server with custom protocol 

```
$ gprocess-man -l 0.0.0.0:8080
$ nc 127.0.0.18080
..
```

- [x] protocol draft, based on  sizeof + protobuf.
- [x] process start / stop
- [x] read stdout / read stderr
- [x] list process.

```[tasklist]
### Tasks
```
